package vista;

import controlador.*;
import java.util.ArrayList;
import modelo.Subestacion;
import javax.swing.table.DefaultTableModel;

public class PanelSubEstacion extends javax.swing.JPanel {

    private ControladorSubestacion controlador = new ControladorSubestacion();
    private ArrayList<Subestacion> subestaciones = new ArrayList<>();
    
    public PanelSubEstacion() {
        initComponents();
        llenarTabla();
        jTable1.setRowSorter(new javax.swing.table.TableRowSorter<>((javax.swing.table.DefaultTableModel) jTable1.getModel()));
    }
    
    public javax.swing.JTable getJTable1(){
        return jTable1;
    }
    
    public void llenarTabla(){
        subestaciones = controlador.obtenerSubestaciones();
        
        DefaultTableModel modeloTabla = (DefaultTableModel) jTable1.getModel();
        modeloTabla.setRowCount(0);
        
        for(Subestacion index : subestaciones){
            String id = index.getID();
            String nombre = index.getNombre();
            String departamento = index.getUbicacion().getDepartamento();
            
            Object[] fila = new Object[]{ id, nombre, departamento };
            modeloTabla.addRow(fila);
        }
  
        if (!subestaciones.isEmpty()) {
            llenarEtiquetas(subestaciones.get(0));
        }
    }
    
    public void llenarEtiquetas(Subestacion subE){
        jLabelinfosub.setText("Informacion Basica");
        jLabelidsub.setText("ID: " + subE.getID());
        jLabelnamesub.setText("Nombre: " + subE.getNombre());
        jLabeloperadorsub.setText("Operador: " + String.join(" - ", subE.getOperadores()));
        jLabelvoltajensub.setText("Voltaje nominal: " + String.valueOf(subE.getVoltajeNominalDeOperacion()) + " kV");
        jLabelubisub.setText("Ubicacion");
        jLabeldptosub.setText("Departamento: " + subE.getUbicacion().getDepartamento());
        jLabelmunicipiosub.setText("Ubicacion: " + subE.getUbicacion().getMunicipio());
        
        String subarea = subE.getUbicacion().getSubAreaOperativa().replace("SubArea", "");
        jLabelsubareasub.setText("Subarea: " + subarea);
    }

                                 


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabelnamesub = new javax.swing.JLabel();
        jLabeloperadorsub = new javax.swing.JLabel();
        jLabelvoltajensub = new javax.swing.JLabel();
        jLabelmunicipiosub = new javax.swing.JLabel();
        jLabeldptosub = new javax.swing.JLabel();
        jLabelsubareasub = new javax.swing.JLabel();
        jLabelidsub = new javax.swing.JLabel();
        jLabelubisub = new javax.swing.JLabel();
        jLabelinfosub = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Departamento"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
        }

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabelnamesub.setText("jLabel1");

        jLabeloperadorsub.setText("jLabel1");

        jLabelvoltajensub.setText("jLabel1");

        jLabelmunicipiosub.setText("jLabel1");

        jLabeldptosub.setText("jLabel1");

        jLabelsubareasub.setText("jLabel1");

        jLabelidsub.setText("jLabel1");

        jLabelubisub.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabelubisub.setText("jLabel1");

        jLabelinfosub.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabelinfosub.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelinfosub, javax.swing.GroupLayout.DEFAULT_SIZE, 619, Short.MAX_VALUE)
                    .addComponent(jLabelidsub, javax.swing.GroupLayout.DEFAULT_SIZE, 619, Short.MAX_VALUE)
                    .addComponent(jLabelubisub, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelnamesub, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabeloperadorsub, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelvoltajensub, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelmunicipiosub, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabeldptosub, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelsubareasub, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabelinfosub)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelidsub)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelnamesub)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabeloperadorsub)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelvoltajensub)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelubisub)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelmunicipiosub)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabeldptosub)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelsubareasub)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(8, 8, 8))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:       
        int filaSeleccionada = jTable1.getSelectedRow();
    
        if(filaSeleccionada != -1){
            int filaReal = jTable1.convertRowIndexToModel(filaSeleccionada);
            Subestacion subestacion = subestaciones.get(filaReal);
            llenarEtiquetas(subestacion);
        }
    }//GEN-LAST:event_jTable1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabeldptosub;
    private javax.swing.JLabel jLabelidsub;
    private javax.swing.JLabel jLabelinfosub;
    private javax.swing.JLabel jLabelmunicipiosub;
    private javax.swing.JLabel jLabelnamesub;
    private javax.swing.JLabel jLabeloperadorsub;
    private javax.swing.JLabel jLabelsubareasub;
    private javax.swing.JLabel jLabelubisub;
    private javax.swing.JLabel jLabelvoltajensub;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
